# Generated by Django 5.1.7 on 2025-03-08 22:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bookname", models.CharField(max_length=30)),
                ("author", models.CharField(max_length=30)),
                ("published_date", models.DateField()),
            ],
        ),
    ]
